package database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.wuhanbus.bean.StopInfo;

import database.greenDao.db.StopInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stopInfoDaoConfig;

    private final StopInfoDao stopInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stopInfoDaoConfig = daoConfigMap.get(StopInfoDao.class).clone();
        stopInfoDaoConfig.initIdentityScope(type);

        stopInfoDao = new StopInfoDao(stopInfoDaoConfig, this);

        registerDao(StopInfo.class, stopInfoDao);
    }
    
    public void clear() {
        stopInfoDaoConfig.clearIdentityScope();
    }

    public StopInfoDao getStopInfoDao() {
        return stopInfoDao;
    }

}
